package com.coffee.responseMapper;

import com.coffee.dto.OrderItemRatingDto;
import com.coffee.request.RateOrderItem;
import com.coffee.request.RateOrderItemRequest;
import com.coffee.response.RateOrderItemResponse;
import org.springframework.stereotype.Component;

import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class OrderRatingResponseMapper {


    public List<OrderItemRatingDto> mapToOrderItemRatingDto(RateOrderItemRequest request) {
        if (request == null || request.getOrderItems() == null) {
            return Collections.emptyList();
        }

        OffsetDateTime now = OffsetDateTime.now();

        return request.getOrderItems().stream()
                .map(item -> OrderItemRatingDto.builder()
                        .id(null) // ID will be generated by the database
                        .orderId(request.getOrderId())
                        .menuItemKey(item.getMenuItemKey())
                        .rating(item.getRating())
                        .comment(item.getComment())
                        .image(null) // image not provided
                        .status(1) // default status
                        .createdAt(now)
                        .updatedAt(now)
                        .userName(request.getUserName())
                        .build())
                .collect(Collectors.toList());
    }

    public RateOrderItemResponse mapToRateOrderItemResponse(List<OrderItemRatingDto> orderItemRatingDtoList) {
        if (orderItemRatingDtoList == null || orderItemRatingDtoList.isEmpty()) {
            return RateOrderItemResponse.builder()
                    .orderItems(Collections.emptyList())
                    .build();
        }

        List<RateOrderItem> rateOrderItems = orderItemRatingDtoList.stream()
                .map(dto -> RateOrderItem.builder()
                        .menuItemKey(dto.getMenuItemKey())
                        .comment(dto.getComment())
                        .rating(dto.getRating())
                        .build())
                .collect(Collectors.toList());

        return RateOrderItemResponse.builder()
                .orderItems(rateOrderItems)
                .build();
    }
}
