package com.coffee.entityMapper;

import com.coffee.dto.OrderMenuItemDto;
import com.coffee.entity.OrderMenuItemEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import java.util.List;

@Mapper(componentModel = "spring")
public interface OrderMenuItemEntityMapper {

    // You can keep this for direct instantiation if not using Spring DI
    // OrderMenuMapper INSTANCE = Mappers.getMapper(OrderMenuMapper.class);

    // Convert Entity to DTO
    OrderMenuItemDto buildDto(OrderMenuItemEntity entity);

    // Convert DTO to Entity
    // When converting DTO to Entity for a new creation, you typically don't map the ID,
    // as it's often generated by the database.
    // Also, createdAt and updatedAt will be handled by the database itself.
    @Mapping(target = "id", ignore = true)
    OrderMenuItemEntity buildEntity(OrderMenuItemDto dto);

    // If you need to update an existing entity from a DTO (e.g., in an update operation)
    // You'd typically ignore the ID here as well, and createdAt/updatedAt
    @Mapping(target = "id", ignore = true)
    void updateEntityFromDto(OrderMenuItemDto dto, @MappingTarget OrderMenuItemEntity entity);

    List<OrderMenuItemDto> buildDtos(List<OrderMenuItemEntity> entities);

    @Mapping(target = "id", ignore = true)
    List<OrderMenuItemEntity> buildEntities(List<OrderMenuItemDto> dtos);
}